---
# Handlers

# Restart squid service
- name: restart squid
  service:
    state: restarted

# Restart firewalld service
- name: restart firewalld
  service:
    name: firewalld
    state: restarted
