---
# ensure squid is installed
- name: ensure squid is installed
  package:
    name: squid
    state: present

# ensure squid is installed
- name: ensure squid-helpers is installed
  package:
    name: squid-helpers
    state: present

# ensure squid-debuginfo is installed
- name: ensure squid is installed
  package:
    name: squid-debuginfo
    state: present

# ensure squid is running
- name: ensure squid is running
  service:
    name: squid
    state: started
