---
# ensure squid is installed
- name: ensure squid is installed
  package:
    name: squid
    state: present

#ensure squid is installed
- name: ensure squid-helpers is installed
  package:
    name: squid-helpers
    state: present
  ignore_errors: yes

#ensure squid-debuginfo is installed
- name: ensure squid is installed
  package:
    name: squid-debuginfo
    state: present
  ignore_errors: yes

- name: copy config files
  copy:
    src: etc/squid/
    dest: /etc/squid/
  notify:
  - restart squid

# make sure security_file_certgen has run
- name: check if ssl_db exists
  stat:
    path: /var/spool/squid/ssl_db
  register: ssl_db_file

# run db create command if above fails
- name: run ssl_db create if necessary
  command:
    cmd: /usr/lib64/squid/security_file_certgen -c -s /var/spool/squid/ssl_db -M 4MB
  become: yes
  become_user: squid
  notify:
  - restart squid
  when: 
    - not ssl_db_file.stat.exists
  
# make sure dhparam exists for DH ciphers
- name: check if dhparam.pem exists
  stat:
    path: /etc/squid/dhparam.pem
  register: dhparam_file

# run db create command if above fails
- name: run dhparam create if necessary
  command: 
    cmd: openssl dhparam -outform PEM -out /etc/squid/dhparam.pem 2048
  notify:
  - restart squid
  when: not dhparam_file.stat.exists

# ensure squid is running
- name: ensure squid is running
  service:
    name: squid
    state: started

- name: SELinux booleans squid_use_tproxy
  seboolean:
    name: squid_use_tproxy
    state: yes
    persistent: yes

- name: SELinux booleans squid_connect_any
  seboolean:
    name: squid_connect_any
    state: yes
    persistent: yes

- name: SELinux ports
  seport:
    ports: 3128,3129,3130
    proto: tcp
    setype: squid_port_t
    state: present

- name: Forward 3129
  iptables:
    table: nat
    chain: PREROUTING
    source: 192.168.56.0/24
    in_interface: ens33
    protocol: tcp
    match: tcp
    destination_port: 80
    jump: REDIRECT
    to_ports: 3129
    comment: Redirect 80 to squid 3129

- name: Forward 3130
  iptables:
    table: nat
    chain: PREROUTING
    source: 192.168.56.0/24
    in_interface: ens33
    protocol: tcp
    match: tcp
    destination_port: 443
    jump: REDIRECT
    to_ports: 3130
    comment: Redirect 443 to squid 3130

- name: SNAT for proxy
  iptables:
    table: nat
    chain: POSTROUTING
    destination: !192.168.56.0/24
    out_interface: ens33
    jump: SNAT
    to_source: 192.168.56.130

# ensure cron job for squid log rotation exists
- name: cron job squid log rotation
  cron:
    name: squid_log_rotation
    hour: "2"
    job: "/usr/local/squid/sbin/squid -k rotate"

# ensure selinux is turned on
- name: selinux turned on
  selinux:
    policy: targeted
    state: enforcing
